language: generic
sudo: required
# ^ required for Docker
services:
  - docker

before_install:
  - docker build -t elohmrow/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elohmrow/docker-react npm run test
#  - docker run elohmrow/docker-react npm run test -- --coverage
# ^ default behavior for npm run test is to 'hang' and wait for input
# travis won't do that, it will exit right away.
# this ensures it doesn't just hang while travis is running

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-1-437158955347"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"