language: generic
sudo: required
# ^ required for Docker
services:
  - docker

before_install:
  - docker build -t elohmrow/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true elohmrow/docker-react npm run test
#  - docker run elohmrow/docker-react npm run test -- --coverage
# ^ default behavior for npm run test is to 'hang' and wait for input
# travis won't do that, it will exit right away.
# this ensures it doesn't just hang while travis is running